version: "3.8"

services:
  # ${API_SERVICE_NAME}:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_SERVICE_PORT}:${API_SERVICE_PORT}"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port $API_SERVICE_PORT